version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  webapp:
    build: ./src/application
    ports:
      - "3000:3000"
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
      - CRAWLER_SERVICE_URL=http://crawler:8001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./src/application:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - ai-service
      - crawler
      - db
    networks:
      - app-network

  crawler:
    build: 
      context: .
      dockerfile: src/crawler/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./utils:/app/utils
    depends_on:
      - db
    networks:
      - app-network

  ai-service:
    build: 
      context: .
      dockerfile: src/inference/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=${OLLAMA_URL}
      - CRAWLER_URL=http://crawler:8001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./models:/app/models
      - ./utils:/app/utils
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./src:/app/src
    depends_on:
      - db
      # - ollama
    networks:
      - app-network

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./models:/root/.ollama
  #     - ./scripts/ollama_entrypoint.sh:/entrypoint.sh
  #   entrypoint: ["/entrypoint.sh"]
  #   # deploy:               # Uncomment this section if using NVIDIA GPUs
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #         - driver: nvidia
  #   #           count: 1
  #   #           capabilities: [gpu]
  #   networks:
  #     - app-network

  # ollama:    # new 
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./models:/root/.ollama
  #     - ./scripts/ollama_entrypoint.sh:/entrypoint.sh
  #   entrypoint: ["/entrypoint.sh"]
  #   networks:
  #     - app-network

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http webapp:3000"
    depends_on:
      - webapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

