version: '3.8'

services:
  webapp:
    build: ./src/application
    ports:
      - "3000:3000"
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
      - CRAWLER_SERVICE_URL=http://crawler:8001
    volumes:
      - ./src/application:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - ai-service
      - crawler
    networks:
      - app-network

  crawler:
    build: 
      context: .
      dockerfile: src/crawler/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./utils:/app/utils
    networks:
      - app-network

  ai-service:
    build: 
      context: .
      dockerfile: src/inference/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=${OLLAMA_URL}
      - CRAWLER_URL=http://crawler:8001
    volumes:
      - ./models:/app/models
      - ./utils:/app/utils
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./src:/app/src
    # depends_on:
    #   - ollama
    networks:
      - app-network

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./models:/root/.ollama
  #     - ./scripts/ollama_entrypoint.sh:/entrypoint.sh
  #   entrypoint: ["/entrypoint.sh"]
  #   networks:
  #     - app-network

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http webapp:3000"
    depends_on:
      - webapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

